### ISSUE TITLE
-u parameter problem

### ISSUE THREAD

**Issue by CCH0124** [c1224412278/Teach-Record#2]
```shell
git push -u ori ori  
```
What does u mean ?

**Comment by pkmogy** [comment]
@CCH0124 當你使用 `-u` 的時候，git會把它設為預設值，當你下次上傳只需要輸入 `git push` 就可以了

@c1224412278 需要修改一下說明

**Comment by CCH0124** [comment]
@pkmogy I got it. Thank.
